const video = document.querySelector ('#video')
const playVideo = document.querySelector ('#play-video')
const stopVideo = document.querySelector ('#stop-video')
const img1 = document.querySelector ('#play-stop-img1')
const img2 = document.querySelector ('#play-stop-img2')

console.log(video)
console.log(playVideo)
console.log(stopVideo)
console.log(img1)
console.log(img2)